- name: Deploying smbot
  hosts: smbot
  become: yes

  tasks:

  - name: Check if smbot exists
    stat:
      path: /etc/systemd/system/smbot.service
    register: smbot_s

  - name: Installing python
    apt:
      pkg:
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
    when: not smbot_s.stat.exists

  - name: Creating service
    copy:
      src: ./smbot.service
      dest: /etc/system/systemd/smbot.service
      owner: root
      group: root
      mode: 0644
    when: not smbot_s.stat.exists
  
  - name: Reloading daemons configs
    systemd:
      daemon_reload: yes
    when: not smbot_s.stat.exists

  - name: Enabling smbot daemon
    systemd:
      name: smbot
      state: stopped
      enabled: yes
    when: not smbot_s.stat.exists

  - name: Copying files
    copy:
      src: "./{{ item }}"
      dest: "/srv/smbot/{{ item }}"
      owner: smbot
      group: smbot
      mode: 0755
    loop:
    - main.py
    - weathercast.py
    - statsm.py
    - keyboard.py
    - smok_ph.py
    - requirements.txt
    - coins.py
    - bj.py
    notify: Restart bot

  handlers:

  - name: Restart bot
    service:
      name: smbot
      state: restarted
